#!/usr/bin/env node

/**
 * Production-Ready Comprehensive Test Suite for Purchase Order Status Update Logic
 * Testing POST /v1/poinvoices/ with Complete Purchase Order Status Management
 * 
 * Test Objectives:
 * 1. Purchase order creation with po_status='in_progress' and ponumber handling
 * 2. POST logic updates purchase order status based on payment amounts
 * 3. Verify poinvoice.purchaseorderstatus matches purchaseorder.po_status
 * 4. Comprehensive error handling, security, and edge case testing
 * 5. Production-ready validation with proper cleanup and rectification steps
 */

import axios from 'axios';
import { randomBytes } from 'crypto';

// Environment configuration
const CONFIG = {
  BASE_URL: process.env.API_BASE_URL || 'http://localhost:5600',
  TIMEOUT: parseInt(process.env.TEST_TIMEOUT) || 15000,
  RETRIES: parseInt(process.env.TEST_RETRIES) || 3,
  VERBOSE: process.env.TEST_VERBOSE !== 'false',
  CLEANUP: process.env.TEST_CLEANUP !== 'false'
};

const POINVOICE_URL = `${CONFIG.BASE_URL}/v1/poinvoices`;
const PURCHASEORDER_URL = `${CONFIG.BASE_URL}/v1/purchaseorders`;

// Track created resources for cleanup
const createdResources = {
  purchaseorders: [],
  poinvoices: []
};

// Test results tracking
let testResults = {
  total: 0,
  passed: 0,
  failed: 0,
  errors: [],
  details: [],
  rectificationSteps: []
};

/**
 * Utility functions
 */
function log(message, type = 'info') {
  if (!CONFIG.VERBOSE && type === 'info') return;
  
  const timestamp = new Date().toISOString();
  const prefix = type === 'error' ? '❌' : type === 'success' ? '✅' : type === 'warning' ? '⚠️' : 'ℹ️';
  console.log(`${prefix} [${timestamp}] ${message}`);
}

function logTest(testName, status, details = '', rectificationSteps = []) {
  testResults.total++;
  if (status === 'passed') {
    testResults.passed++;
    log(`TEST PASSED: ${testName}${details ? ' - ' + details : ''}`, 'success');
  } else {
    testResults.failed++;
    testResults.errors.push(`${testName}: ${details}`);
    testResults.rectificationSteps.push({ testName, steps: rectificationSteps });
    log(`TEST FAILED: ${testName}${details ? ' - ' + details : ''}`, 'error');
    if (rectificationSteps.length > 0) {
      log(`RECTIFICATION STEPS:`, 'warning');
      rectificationSteps.forEach((step, index) => {
        log(`  ${index + 1}. ${step}`, 'warning');
      });
    }
  }
  testResults.details.push({ testName, status, details, rectificationSteps });
}

function generateUniqueId() {
  return Date.now() + Math.floor(Math.random() * 1000);
}

function generateUniquePONumber(prefix = 'TEST') {
  const timestamp = Date.now();
  const random = randomBytes(2).toString('hex').toUpperCase();
  return `${prefix}-PO-${timestamp}-${random}`;
}

function generateUniqueInvoiceNumber(prefix = 'INV') {
  const timestamp = Date.now();
  const random = randomBytes(2).toString('hex').toUpperCase();
  return `${prefix}_${timestamp}_${random}`;
}

async function makeRequest(method, url, data = null, expectedStatus = null) {
  try {
    const config = {
      method,
      url,
      timeout: CONFIG.TIMEOUT,
      headers: {
        'Content-Type': 'application/json'
      }
    };
    
    if (data) {
      config.data = data;
    }

    const response = await axios(config);
    
    if (expectedStatus && response.status !== expectedStatus) {
      throw new Error(`Expected status ${expectedStatus}, got ${response.status}`);
    }
    
    return response;
  } catch (error) {
    if (error.response) {
      return error.response;
    }
    throw error;
  }
}

async function waitForCondition(conditionFn, timeout = 5000, interval = 500) {
  const startTime = Date.now();
  
  while (Date.now() - startTime < timeout) {
    try {
      const result = await conditionFn();
      if (result) return result;
    } catch (error) {
      // Ignore errors and continue polling
    }
    await new Promise(resolve => setTimeout(resolve, interval));
  }
  
  throw new Error(`Condition not met within ${timeout}ms`);
}

/**
 * Data generation functions
 */
function createTestPurchaseOrder(ponumber = null) {
  const autoGeneratedPONumber = ponumber || generateUniquePONumber('FREAU-TEQIT');
  
  return {
    ponumber: autoGeneratedPONumber,
    prnumber: `FREAU-PR-${Date.now()}`,
    companyname: "Aromazen Test",
    companyaddress: "Test Street, Test City, TC",
    contactname: "Test Contact",
    phonenumber: 9785463120,
    gstnumber: "33TESTGST001Z",
    io_companyname: "Aromazen Test",
    io_companyaddress: "Test Street, Test City, TC", 
    io_contactname: "Test Contact",
    io_phonenumber: 9785463120,
    io_gstnumber: "33TESTGST001Z",
    dt_companyname: "",
    dt_companyaddress: "",
    dt_contactname: "",
    dt_phonenumber: null,
    dt_gstnumber: "",
    supplierid: 97, // Use existing supplier ID
    subtotal: 2000,
    discount: 0,
    sgst: 6,
    cgst: 6,
    payabletaxamount: 240,
    total: 2520,
    product: {
      items: [
        { id: 1, name: "Test Product - Status Update", quantity: 10 }
      ]
    },
    po_status: "in_progress", // Explicitly set for testing
    supplieraddress: "12, Test Street, Chennai, Tamil Nadu, India, 600130",
    suppliercompanyname: "Fresh Aura Test",
    supplierphonenumber: 8974563120,
    suppliergstnumber: "33TESTSUP001Z",
    instructions: "Test delivery for status update",
    fileurl: null,
    invoiceurl: [],
    sameasinvoice: false,
    paymentterms: "30",
    overduedate: null,
    comments: "Test automation for status update",
    suppliertype: "local"
  };
}

function createTestPoinvoice(ponumber, invoiceAmount, paymentAmount, invoiceType = 'partial') {
  const uniqueId = generateUniqueId();
  const invoiceNumber = generateUniqueInvoiceNumber();
  const currentTimestamp = Math.floor(Date.now() / 1000);
  
  return {
    invoiceamount: invoiceAmount,
    ponumber: ponumber,
    invoicedate: currentTimestamp,
    invoicenumber: invoiceNumber,
    invoiceurl: `https://test-storage.example.com/${ponumber}/invoice_${invoiceNumber}.pdf`,
    paymentdata: [
      {
        id: uniqueId,
        comments: `Test ${invoiceType} payment for status update`,
        paymentdate: new Date().toISOString().split('T')[0],
        paymenttype: invoiceType === 'partial' ? 'Part Payment' : 'Full Payment',
        paymentamount: paymentAmount,
        paymentmethod: 'banktransfer',
        transactionid: `TXN_TEST_${uniqueId}`,
        receiptcomments: `Test payment received - ${invoiceType}`
      }
    ],
    createddate: currentTimestamp,
    modifieddate: currentTimestamp,
    balanceamount: invoiceAmount - paymentAmount,
    iscreditpayment: false,
    paymentduedate: currentTimestamp + (30 * 24 * 60 * 60), // 30 days from now
    invoicestatus: paymentAmount >= invoiceAmount ? 'paid' : 'partial',
    pototal: 2520, // Match PO total
    purchaseorderstatus: "in_progress", // Initial status
    transportationcharges: null,
    exchangeamount: null,
    customdutytaxamount: null,
    suppliertype: "local",
    customdutychallanurl: null,
    billofentryurl: null
  };
}

/**
 * Test Functions
 */

async function testServerAvailability() {
  log('Testing Server Availability...');
  
  try {
    const response = await makeRequest('GET', `${CONFIG.BASE_URL}/health`);
    
    if (response.status === 200 || response.status === 404) {
      logTest('Server Availability', 'passed', 'Server is responding');
      return { success: true };
    } else {
      logTest('Server Availability', 'failed', `Server returned status ${response.status}`, [
        'Check if the server is running on http://localhost:5600',
        'Verify the API base URL configuration',
        'Check network connectivity and firewall settings'
      ]);
      return { success: false };
    }
  } catch (error) {
    logTest('Server Availability', 'failed', error.message, [
      'Start the server using npm start or node server.js',
      'Check if port 5600 is available and not blocked',
      'Verify the application configuration and environment variables'
    ]);
    return { success: false };
  }
}

async function testPurchaseOrderCreation() {
  log('Testing Purchase Order Creation with po_status=in_progress...');
  
  try {
    const testPO = createTestPurchaseOrder();
    const response = await makeRequest('POST', PURCHASEORDER_URL, testPO, 201);
    
    if (response.status === 201) {
      const po = response.data.data;
      createdResources.purchaseorders.push(po.ponumber);
      
      // Check po_status
      if (po.po_status === 'in_progress') {
        logTest('Purchase Order Creation - Status', 'passed', `Created PO ${po.ponumber} with status in_progress`);
      } else {
        logTest('Purchase Order Creation - Status', 'failed', `po_status is ${po.po_status}, expected in_progress`, [
          'Check src/services/purchaseorder.service.ts create method',
          'Ensure po_status is set to "in_progress" by default in line ~96',
          'Verify that the createData object includes po_status: "in_progress"',
          'Check if database constraints or triggers are overriding the default value'
        ]);
      }
      
      // Check ponumber (manual generation in this implementation)
      if (po.ponumber && po.ponumber.length > 0) {
        logTest('Purchase Order Creation - PONumber', 'passed', `PONumber ${po.ponumber} is present`);
      } else {
        logTest('Purchase Order Creation - PONumber', 'failed', 'PONumber is missing or empty', [
          'Current implementation requires manual ponumber in request body',
          'To implement auto-generation: Add database trigger or modify service logic',
          'For database trigger: CREATE TRIGGER on purchaseorder table',
          'For service logic: Generate ponumber in purchaseorder.service.ts if not provided'
        ]);
      }
      
      return { success: true, po };
    } else {
      logTest('Purchase Order Creation', 'failed', `HTTP ${response.status}: ${response.data?.message || 'Unknown error'}`, [
        'Check required fields in purchase order schema',
        'Verify supplier with ID 97 exists in database',
        'Check database connection and constraints',
        'Review validation logic in purchaseorder.controller.ts'
      ]);
      return { success: false, error: response.data?.message };
    }
  } catch (error) {
    logTest('Purchase Order Creation', 'failed', error.message, [
      'Verify API endpoint /v1/purchaseorders exists',
      'Check request data format matches schema',
      'Ensure database is running and accessible',
      'Review error logs for specific database or validation errors'
    ]);
    return { success: false, error: error.message };
  }
}

async function testPoinvoicePartialPayment(ponumber) {
  log('Testing Poinvoice with Partial Payment (should update PO status to partially_fulfilled)...');
  
  try {
    const poinvoiceData = createTestPoinvoice(ponumber, 1000, 600, 'partial');
    const response = await makeRequest('POST', POINVOICE_URL, poinvoiceData, 201);
    
    if (response.status === 201) {
      const poinvoice = response.data.data;
      createdResources.poinvoices.push(poinvoice.id);
      
      logTest('Poinvoice Partial Payment - Creation', 'passed', `Created poinvoice ID ${poinvoice.id}`);
      
      // Wait for PO status update
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const poResponse = await makeRequest('GET', `${PURCHASEORDER_URL}?ponumber=${ponumber}`);
      if (poResponse.status === 200 && poResponse.data.data.length > 0) {
        const po = poResponse.data.data[0];
        
        if (po.po_status === 'partially_fulfilled') {
          logTest('Poinvoice Partial Payment - PO Status Update', 'passed', 'PO status updated to partially_fulfilled');
        } else {
          logTest('Poinvoice Partial Payment - PO Status Update', 'failed', `Status is ${po.po_status}, expected partially_fulfilled`, [
            'Check src/services/poinvoice.service.ts updatePurchaseOrderStatus method',
            'Verify payment amount extraction logic in extractPaymentAmount method',
            'Ensure database transaction is working properly (lines 196-220)',
            'Check if ponumber lookup is finding the correct purchase order',
            'Verify totalPayments calculation includes existing payments'
          ]);
        }
        
        // Check if poinvoice.purchaseorderstatus matches
        if (poinvoice.purchaseorderstatus === po.po_status) {
          logTest('Poinvoice Partial Payment - Status Sync', 'passed', 'Poinvoice purchaseorderstatus matches PO status');
        } else {
          logTest('Poinvoice Partial Payment - Status Sync', 'failed', `Poinvoice status is ${poinvoice.purchaseorderstatus}, PO status is ${po.po_status}`, [
            'Check poinvoice.service.ts create method lines 210-217',
            'Ensure purchaseorderstatus is updated after PO status change',
            'Verify the transaction includes both PO and poinvoice updates',
            'Check if the updatedPO is being fetched correctly after status update'
          ]);
        }
      }
      
      return { success: true, poinvoice };
    } else {
      logTest('Poinvoice Partial Payment', 'failed', `HTTP ${response.status}: ${response.data?.message || 'Unknown error'}`, [
        'Verify ponumber exists in purchase order table',
        'Check payment data format matches expected schema',
        'Ensure all required fields are provided',
        'Review poinvoice.controller.ts createPoinvoice method'
      ]);
      return { success: false, error: response.data?.message };
    }
  } catch (error) {
    logTest('Poinvoice Partial Payment', 'failed', error.message, [
      'Check API endpoint /v1/poinvoices exists and is accessible',
      'Verify request data format and field types',
      'Ensure database connection is stable',
      'Review application logs for detailed error information'
    ]);
    return { success: false, error: error.message };
  }
}

async function testPoinvoiceFullPayment(ponumber) {
  log('Testing Poinvoice with Full Payment (should update PO status to fulfilled)...');
  
  try {
    // Create second payment to reach total (600 already paid, need 1920 more for total 2520)
    const poinvoiceData = createTestPoinvoice(ponumber, 1920, 1920, 'full');
    const response = await makeRequest('POST', POINVOICE_URL, poinvoiceData, 201);
    
    if (response.status === 201) {
      const poinvoice = response.data.data;
      createdResources.poinvoices.push(poinvoice.id);
      
      logTest('Poinvoice Full Payment - Creation', 'passed', `Created poinvoice ID ${poinvoice.id}`);
      
      // Wait for PO status update
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const poResponse = await makeRequest('GET', `${PURCHASEORDER_URL}?ponumber=${ponumber}`);
      if (poResponse.status === 200 && poResponse.data.data.length > 0) {
        const po = poResponse.data.data[0];
        
        if (po.po_status === 'fulfilled') {
          logTest('Poinvoice Full Payment - PO Status Update', 'passed', 'PO status updated to fulfilled');
        } else {
          logTest('Poinvoice Full Payment - PO Status Update', 'failed', `Status is ${po.po_status}, expected fulfilled`, [
            'Check total payments calculation in calculateTotalPaymentsForPO method',
            'Verify that totalPayments >= poTotal condition is working (line 94)',
            'Ensure parseFloat conversion of PO total is correct',
            'Check if multiple poinvoices are being summed correctly',
            'Verify database precision for decimal calculations'
          ]);
        }
      }
      
      return { success: true, poinvoice };
    } else {
      logTest('Poinvoice Full Payment', 'failed', `HTTP ${response.status}: ${response.data?.message || 'Unknown error'}`, [
        'Verify sufficient balance remains for payment',
        'Check payment amount does not exceed remaining balance',
        'Ensure ponumber still exists and is valid',
        'Review business logic for full payment validation'
      ]);
      return { success: false, error: response.data?.message };
    }
  } catch (error) {
    logTest('Poinvoice Full Payment', 'failed', error.message, [
      'Check calculation logic for remaining payment amount',
      'Verify payment data structure and validation',
      'Ensure no race conditions in concurrent payment processing',
      'Review transaction isolation levels'
    ]);
    return { success: false, error: error.message };
  }
}

async function testInvalidInputs() {
  log('Testing Invalid Input Handling...');
  
  const tests = [
    {
      name: 'Invalid PONumber',
      data: createTestPoinvoice('INVALID-PO-NUMBER', 1000, 500),
      expectedStatus: 400,
      rectificationSteps: [
        'Add ponumber validation in poinvoice.service.ts create method',
        'Check if purchase order exists before creating poinvoice',
        'Return appropriate error message for non-existent ponumber',
        'Consider adding foreign key constraint on ponumber field'
      ]
    },
    {
      name: 'Negative Payment Amount',
      data: { ...createTestPoinvoice('TEST-PO-123', 1000, -100), paymentdata: [{ paymentamount: -100 }] },
      expectedStatus: 400,
      rectificationSteps: [
        'Add payment amount validation in schema (src/schemas/poinvoice.schema.ts)',
        'Use z.number().positive() for paymentamount validation',
        'Add business logic validation in extractPaymentAmount method',
        'Return clear error message for negative amounts'
      ]
    },
    {
      name: 'Missing Required Fields',
      data: { invoiceamount: 1000 }, // Missing ponumber
      expectedStatus: 400,
      rectificationSteps: [
        'Update createPoinvoiceSchema to mark ponumber as required',
        'Change z.string().max(500).optional() to z.string().max(500)',
        'Add validation in controller to check required fields',
        'Return specific error messages for missing fields'
      ]
    }
  ];
  
  for (const test of tests) {
    try {
      const response = await makeRequest('POST', POINVOICE_URL, test.data);
      
      if (response.status === test.expectedStatus) {
        logTest(`Invalid Input - ${test.name}`, 'passed', `Correctly rejected with status ${response.status}`);
      } else {
        logTest(`Invalid Input - ${test.name}`, 'failed', `Expected status ${test.expectedStatus}, got ${response.status}`, test.rectificationSteps);
      }
    } catch (error) {
      logTest(`Invalid Input - ${test.name}`, 'failed', error.message, test.rectificationSteps);
    }
  }
}

async function testSecurityVulnerabilities() {
  log('Testing Security Vulnerabilities...');
  
  const securityTests = [
    {
      name: 'SQL Injection in PONumber',
      data: createTestPoinvoice("'; DROP TABLE poinvoice; --", 1000, 500),
      rectificationSteps: [
        'Current implementation uses Prisma ORM which prevents SQL injection',
        'Verify all database queries use parameterized statements',
        'Add input sanitization for special characters if needed',
        'Review dynamicFindUnique implementation for security'
      ]
    },
    {
      name: 'XSS in Comments',
      data: { 
        ...createTestPoinvoice('TEST-PO-XSS', 1000, 500),
        paymentdata: [{ comments: '<script>alert("xss")</script>', paymentamount: 500 }]
      },
      rectificationSteps: [
        'Add input sanitization in poinvoice controller',
        'Use DOMPurify or similar library for HTML sanitization',
        'Validate and escape special characters in text fields',
        'Implement Content Security Policy (CSP) headers'
      ]
    }
  ];
  
  for (const test of securityTests) {
    try {
      const response = await makeRequest('POST', POINVOICE_URL, test.data);
      
      // Security tests should either be rejected or handled safely
      if (response.status >= 400) {
        logTest(`Security - ${test.name}`, 'passed', 'Malicious input was rejected');
      } else {
        logTest(`Security - ${test.name}`, 'warning', 'Input was accepted - verify sanitization', test.rectificationSteps);
      }
    } catch (error) {
      logTest(`Security - ${test.name}`, 'passed', 'Request was blocked or failed safely');
    }
  }
}

async function testGetOperations() {
  log('Testing GET Operations...');
  
  try {
    // Test GET all poinvoices
    const allResponse = await makeRequest('GET', POINVOICE_URL);
    
    if (allResponse.status === 200) {
      const data = allResponse.data.data;
      if (Array.isArray(data)) {
        logTest('GET All Poinvoices', 'passed', `Retrieved ${data.length} poinvoices`);
        
        // Check if purchaseorderstatus field is present
        if (data.length > 0 && data[0].purchaseorderstatus !== undefined) {
          logTest('GET - Purchaseorderstatus Field', 'passed', 'purchaseorderstatus field is present in response');
        } else {
          logTest('GET - Purchaseorderstatus Field', 'failed', 'purchaseorderstatus field is missing', [
            'Check poinvoice schema includes purchaseorderstatus field',
            'Verify formatPoinvoiceForAPI function includes all fields',
            'Ensure database migration includes purchaseorderstatus column',
            'Check if field is being filtered out in response formatting'
          ]);
        }
        
        // Test specific poinvoice GET if we have created ones
        if (createdResources.poinvoices.length > 0) {
          const poinvoiceId = createdResources.poinvoices[0];
          const singleResponse = await makeRequest('GET', `${POINVOICE_URL}/${poinvoiceId}`);
          
          if (singleResponse.status === 200) {
            logTest('GET Single Poinvoice', 'passed', `Retrieved poinvoice ${poinvoiceId}`);
          } else {
            logTest('GET Single Poinvoice', 'failed', `Failed to retrieve poinvoice ${poinvoiceId}`, [
              'Check if poinvoice ID exists in database',
              'Verify GET /:id route is properly configured',
              'Check findById method in poinvoice.service.ts',
              'Ensure proper error handling for non-existent records'
            ]);
          }
        }
      } else {
        logTest('GET All Poinvoices', 'failed', 'Response data is not an array', [
          'Check response format in poinvoice.controller.ts getPoinvoices method',
          'Verify pagination result structure',
          'Ensure proper data formatting in response',
          'Check if API response wrapper is correct'
        ]);
      }
    } else {
      logTest('GET All Poinvoices', 'failed', `HTTP ${allResponse.status}`, [
        'Check if GET /v1/poinvoices route is properly configured',
        'Verify database connection for read operations',
        'Check authentication/authorization if required',
        'Review server logs for specific errors'
      ]);
    }
  } catch (error) {
    logTest('GET Operations', 'failed', error.message, [
      'Ensure API server is running and accessible',
      'Check network connectivity',
      'Verify endpoint exists and is properly configured',
      'Review CORS settings if testing from browser'
    ]);
  }
}

async function testPerformanceAndConcurrency() {
  log('Testing Performance and Concurrency...');
  
  try {
    // Create a test PO for performance testing
    const testPO = createTestPurchaseOrder();
    const poResponse = await makeRequest('POST', PURCHASEORDER_URL, testPO, 201);
    
    if (poResponse.status === 201) {
      const ponumber = poResponse.data.data.ponumber;
      createdResources.purchaseorders.push(ponumber);
      
      // Test concurrent requests
      const concurrentRequests = [];
      for (let i = 0; i < 5; i++) {
        const poinvoiceData = createTestPoinvoice(ponumber, 100, 50 + i); // Different amounts
        concurrentRequests.push(makeRequest('POST', POINVOICE_URL, poinvoiceData));
      }
      
      const startTime = Date.now();
      const responses = await Promise.allSettled(concurrentRequests);
      const endTime = Date.now();
      
      const successfulResponses = responses.filter(r => r.status === 'fulfilled' && r.value.status === 201);
      
      logTest('Performance - Concurrent Requests', 'passed', 
        `${successfulResponses.length}/5 requests succeeded in ${endTime - startTime}ms`);
      
      // Add created poinvoices to cleanup list
      successfulResponses.forEach(response => {
        if (response.value.data.data.id) {
          createdResources.poinvoices.push(response.value.data.data.id);
        }
      });
      
      if (endTime - startTime > 5000) {
        logTest('Performance - Response Time', 'warning', 
          `Slow response time: ${endTime - startTime}ms`, [
          'Optimize database queries in poinvoice service',
          'Add database indexes on frequently queried fields (ponumber)',
          'Consider implementing caching for purchase order lookups',
          'Review database connection pool settings',
          'Consider using read replicas for GET operations'
        ]);
      } else {
        logTest('Performance - Response Time', 'passed', `Good response time: ${endTime - startTime}ms`);
      }
    }
  } catch (error) {
    logTest('Performance and Concurrency', 'failed', error.message, [
      'Check server capacity and resource limits',
      'Verify database connection pool configuration',
      'Review application performance metrics',
      'Consider load balancing for high concurrency'
    ]);
  }
}

async function cleanupResources() {
  if (!CONFIG.CLEANUP) {
    log('Cleanup disabled, keeping test data');
    return;
  }
  
  log('Cleaning up test resources...');
  
  // Clean up poinvoices first (due to foreign key constraints)
  for (const poinvoiceId of createdResources.poinvoices) {
    try {
      await makeRequest('DELETE', `${POINVOICE_URL}/${poinvoiceId}`);
      log(`Deleted poinvoice ${poinvoiceId}`);
    } catch (error) {
      log(`Failed to delete poinvoice ${poinvoiceId}: ${error.message}`, 'warning');
    }
  }
  
  // Clean up purchase orders
  for (const ponumber of createdResources.purchaseorders) {
    try {
      // Note: Implement DELETE endpoint if not available
      const deleteResponse = await makeRequest('DELETE', `${PURCHASEORDER_URL}/${ponumber}`);
      if (deleteResponse.status < 400) {
        log(`Deleted purchase order ${ponumber}`);
      }
    } catch (error) {
      log(`Failed to delete purchase order ${ponumber}: ${error.message}`, 'warning');
      // Consider manual cleanup or implement cascade delete
    }
  }
}

async function runAllTests() {
  console.log('🚀 Starting Comprehensive Purchase Order Status Update Tests');
  console.log(`📊 Base URL: ${CONFIG.BASE_URL}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  
  try {
    // 1. Test server availability
    const serverTest = await testServerAvailability();
    if (!serverTest.success) {
      console.log('❌ Server not available, stopping tests');
      return;
    }
    
    // 2. Test Purchase Order Creation
    const poTest = await testPurchaseOrderCreation();
    let testPonumber = null;
    
    if (poTest.success) {
      testPonumber = poTest.po.ponumber;
    } else {
      // Create a fallback PO for remaining tests
      log('Creating fallback PO for remaining tests...', 'warning');
      const fallbackPO = createTestPurchaseOrder();
      const fallbackResponse = await makeRequest('POST', PURCHASEORDER_URL, fallbackPO);
      if (fallbackResponse.status === 201) {
        testPonumber = fallbackResponse.data.data.ponumber;
        createdResources.purchaseorders.push(testPonumber);
      }
    }
    
    if (testPonumber) {
      // 3. Test partial payment and status update
      await testPoinvoicePartialPayment(testPonumber);
      
      // 4. Test full payment and status update
      await testPoinvoiceFullPayment(testPonumber);
    }
    
    // 5. Test invalid inputs
    await testInvalidInputs();
    
    // 6. Test security
    await testSecurityVulnerabilities();
    
    // 7. Test GET operations
    await testGetOperations();
    
    // 8. Test performance and concurrency
    await testPerformanceAndConcurrency();
    
  } catch (error) {
    log(`Unexpected error during test execution: ${error.message}`, 'error');
  } finally {
    // 9. Cleanup
    await cleanupResources();
    
    // 10. Print results
    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('📋 TEST RESULTS SUMMARY');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(`✅ Total Tests: ${testResults.total}`);
    console.log(`✅ Passed: ${testResults.passed}`);
    console.log(`❌ Failed: ${testResults.failed}`);
    console.log(`📊 Success Rate: ${((testResults.passed / testResults.total) * 100).toFixed(1)}%`);
    
    if (testResults.failed > 0) {
      console.log('\n🔧 RECTIFICATION STEPS FOR FAILED TESTS:');
      console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      
      testResults.rectificationSteps.forEach((item, index) => {
        if (item.steps.length > 0) {
          console.log(`\n${index + 1}. ${item.testName}:`);
          item.steps.forEach((step, stepIndex) => {
            console.log(`   ${stepIndex + 1}. ${step}`);
          });
        }
      });
    }
    
    console.log('\n🎯 PRODUCTION READINESS CHECKLIST:');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('□ All tests passing (100% success rate)');
    console.log('□ Purchase order status transitions working correctly');
    console.log('□ Payment calculations accurate');
    console.log('□ Database transactions atomic');
    console.log('□ Error handling comprehensive');
    console.log('□ Security vulnerabilities addressed');
    console.log('□ Performance within acceptable limits');
    console.log('□ Documentation updated');
    
    if (testResults.failed === 0) {
      console.log('\n🎉 ALL TESTS PASSED! API is production-ready! 🎉');
    } else {
      console.log('\n⚠️  Please address failed tests before production deployment ⚠️');
    }
  }
}

// Run tests if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  runAllTests().catch(console.error);
}

export {
  runAllTests,
  testPurchaseOrderCreation,
  testPoinvoicePartialPayment,
  testPoinvoiceFullPayment,
  createTestPurchaseOrder,
  createTestPoinvoice
}; 