-- Return source module: reason rules, requests, and request attachments.

CREATE TABLE "return_reason_rules" (
  "id" SERIAL PRIMARY KEY,
  "reasoncode" VARCHAR(100) NOT NULL UNIQUE,
  "reasonname" VARCHAR(255) NOT NULL,
  "source" VARCHAR(50) NOT NULL DEFAULT 'customer',
  "aliases" TEXT[] NOT NULL,
  "allowedresolutions" TEXT[] NOT NULL,
  "minimumraisewindowhours" INTEGER,
  "photorequired" BOOLEAN NOT NULL DEFAULT true,
  "videorequired" BOOLEAN NOT NULL DEFAULT false,
  "packagephotorequired" BOOLEAN NOT NULL DEFAULT false,
  "packagephotooptional" BOOLEAN NOT NULL DEFAULT false,
  "unboxingvideorequired" BOOLEAN NOT NULL DEFAULT false,
  "unboxingvideooptional" BOOLEAN NOT NULL DEFAULT false,
  "openedpackageallowed" BOOLEAN NOT NULL DEFAULT true,
  "pickuprequired" BOOLEAN NOT NULL DEFAULT true,
  "evidencefirstapproval" BOOLEAN NOT NULL DEFAULT false,
  "autocreatepickup" BOOLEAN NOT NULL DEFAULT false,
  "reverseshippingchargebearer" VARCHAR(50),
  "notes" TEXT,
  "status" VARCHAR(50) NOT NULL DEFAULT 'active',
  "createddate" BIGINT,
  "modifieddate" BIGINT
);

CREATE INDEX "idx_return_reason_rules_source" ON "return_reason_rules" ("source");
CREATE INDEX "idx_return_reason_rules_status" ON "return_reason_rules" ("status");

CREATE TABLE "return_requests" (
  "id" SERIAL PRIMARY KEY,
  "requestnumber" VARCHAR(100) NOT NULL UNIQUE,
  "orderid" INTEGER,
  "orderlineid" INTEGER,
  "customerid" INTEGER,
  "requesttype" VARCHAR(50) NOT NULL,
  "source" VARCHAR(50) NOT NULL DEFAULT 'customer',
  "reason" VARCHAR(255) NOT NULL,
  "reasoncode" VARCHAR(100) NOT NULL,
  "requestedquantity" INTEGER NOT NULL DEFAULT 1,
  "requestedresolution" VARCHAR(100),
  "ispackageopened" BOOLEAN,
  "additionalremarks" TEXT,
  "evidence_review_status" VARCHAR(50) NOT NULL DEFAULT 'pending',
  "pickupflow" VARCHAR(50),
  "reverse_shipment_tracking_id" VARCHAR(500),
  "reverse_shipment_provider" VARCHAR(100),
  "auto_create_pickup" BOOLEAN NOT NULL DEFAULT false,
  "pickup_created_by" VARCHAR(50),
  "logistics_provider_source" VARCHAR(100),
  "reverse_shipping_charge_bearer" VARCHAR(50),
  "reverse_shipping_charge_adjustment" VARCHAR(100),
  "status" VARCHAR(100) NOT NULL DEFAULT 'requested',
  "createdby" INTEGER,
  "modifiedby" INTEGER,
  "createddate" BIGINT,
  "modifieddate" BIGINT,
  CONSTRAINT "return_requests_orderid_fkey" FOREIGN KEY ("orderid") REFERENCES "orders" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "return_requests_orderlineid_fkey" FOREIGN KEY ("orderlineid") REFERENCES "orderline" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "return_requests_customerid_fkey" FOREIGN KEY ("customerid") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "idx_return_requests_orderid" ON "return_requests" ("orderid");
CREATE INDEX "idx_return_requests_orderlineid" ON "return_requests" ("orderlineid");
CREATE INDEX "idx_return_requests_customerid" ON "return_requests" ("customerid");
CREATE INDEX "idx_return_requests_source" ON "return_requests" ("source");
CREATE INDEX "idx_return_requests_status" ON "return_requests" ("status");
CREATE INDEX "idx_return_requests_reasoncode" ON "return_requests" ("reasoncode");

CREATE TABLE "return_request_attachments" (
  "id" SERIAL PRIMARY KEY,
  "returnrequestid" INTEGER NOT NULL,
  "attachmenttype" VARCHAR(100) NOT NULL,
  "fileurl" TEXT NOT NULL,
  "isrequired" BOOLEAN NOT NULL DEFAULT false,
  "uploadedbycustomerid" INTEGER,
  "uploadeddate" BIGINT,
  "status" VARCHAR(50) NOT NULL DEFAULT 'active',
  CONSTRAINT "return_request_attachments_request_fkey" FOREIGN KEY ("returnrequestid") REFERENCES "return_requests" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "return_request_attachments_customer_fkey" FOREIGN KEY ("uploadedbycustomerid") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "idx_return_request_attachments_request" ON "return_request_attachments" ("returnrequestid");
CREATE INDEX "idx_return_request_attachments_status" ON "return_request_attachments" ("status");

INSERT INTO "return_reason_rules" (
  "reasoncode",
  "reasonname",
  "source",
  "aliases",
  "allowedresolutions",
  "minimumraisewindowhours",
  "photorequired",
  "videorequired",
  "packagephotorequired",
  "packagephotooptional",
  "unboxingvideorequired",
  "unboxingvideooptional",
  "openedpackageallowed",
  "pickuprequired",
  "evidencefirstapproval",
  "autocreatepickup",
  "reverseshippingchargebearer",
  "notes",
  "status",
  "createddate",
  "modifieddate"
) VALUES
  (
    'wrongly_ordered',
    'Wrongly Ordered',
    'customer',
    ARRAY['Wrongly Ordered', 'Changed Mind'],
    ARRAY['refund', 'complete_return'],
    NULL,
    true,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    'customer',
    'Customer-side reason. Package must be unopened; reverse charge handling requires business confirmation.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'wrong_item_received',
    'Wrong Item Received',
    'customer',
    ARRAY['Wrong Item Received', 'Wrong Product'],
    ARRAY['replacement', 'refund'],
    NULL,
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    'nivaana',
    'Nivaana-side issue. Product should be kept intact for pickup and verification.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'damaged_product',
    'Damaged Product',
    'customer',
    ARRAY['Damaged Product'],
    ARRAY['replacement', 'refund'],
    48,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    true,
    false,
    'nivaana',
    'Must be raised within 48 hours from delivery. Package photo and unboxing video are optional.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'missing_product',
    'Missing Product',
    'customer',
    ARRAY['Missing Product'],
    ARRAY['ship_missing_item', 'partial_refund', 'complete_return'],
    NULL,
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    'nivaana',
    'Pickup is required only when the selected resolution is complete_return.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'defective_product',
    'Defective Product',
    'customer',
    ARRAY['Defective Product'],
    ARRAY['replacement', 'refund'],
    NULL,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    'nivaana',
    'Photo and video evidence are mandatory.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'leakage_broken_bottle',
    'Leakage / Broken Bottle',
    'customer',
    ARRAY['Leakage / Broken Bottle', 'Leakage', 'Broken Bottle'],
    ARRAY['replacement', 'refund'],
    NULL,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    'nivaana',
    'Photo and video evidence are mandatory.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'customer_unreachable',
    'Customer Unreachable',
    'delivery_partner',
    ARRAY['Customer unreachable', 'Customer not reachable'],
    ARRAY[]::TEXT[],
    NULL,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    NULL,
    'Delivery partner RTO reason.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'wrong_address',
    'Wrong Address',
    'delivery_partner',
    ARRAY['Wrong address', 'Incorrect address', 'Incomplete delivery address'],
    ARRAY[]::TEXT[],
    NULL,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    NULL,
    'Delivery partner RTO reason.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'customer_refused_delivery',
    'Customer Refused Delivery',
    'delivery_partner',
    ARRAY['Customer refused', 'Customer refused delivery'],
    ARRAY[]::TEXT[],
    NULL,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    NULL,
    'Delivery partner RTO reason.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  ),
  (
    'delivery_attempt_failed',
    'Delivery Attempt Failed',
    'delivery_partner',
    ARRAY['Delivery attempt failed', 'Delivery attempts failed'],
    ARRAY[]::TEXT[],
    NULL,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    NULL,
    'Delivery partner RTO reason.',
    'active',
    EXTRACT(EPOCH FROM NOW())::BIGINT,
    EXTRACT(EPOCH FROM NOW())::BIGINT
  )
ON CONFLICT ("reasoncode") DO NOTHING;
