import { z } from 'zod';

// Orderline schema based on actual database fields from prisma schema  
export const createOrderlineSchema = z.object({
  orderid: z.number().optional(),
  productid: z.number().optional(),
  userid: z.number().optional(),
  addressid: z.number().optional(),
  productamount: z.number().optional(),
  discountamount: z.number().optional(),
  orderamount: z.number().optional(),
  quantity: z.number().optional(),
  merchanttransactionid: z.string().max(250).optional(),
  productname: z.string().max(1200).optional(),
  productshortname: z.string().max(160).optional(),
  productcategory: z.string().max(500).optional(),
  productcolour: z.string().max(500).optional(),
  readytodispatchdate: z.number().optional(),
  delivereddate: z.number().optional(),
  cancelleddate: z.number().optional(),
  returneddate: z.number().optional(),
  orderstatus: z.string().max(500).optional(),
  uniqueordderid: z.string().max(500).optional(),
  orderlinenumber: z.string().max(500).optional(),
  deliveryfrom: z.string().max(500).optional(),
  location: z.string().max(500).optional(),
  dispatcheddate: z.number().optional(),
  ordereddate: z.number().optional(),
  paymentfaileddate: z.number().optional(),
  createddate: z.number().optional(),
  modifieddate: z.number().optional(),
}).passthrough();

export const updateOrderlineSchema = z.object({
  orderid: z.number().optional(),
  productid: z.number().optional(),
  userid: z.number().optional(),
  addressid: z.number().optional(),
  productamount: z.number().optional(),
  discountamount: z.number().optional(),
  orderamount: z.number().optional(),
  quantity: z.number().optional(),
  merchanttransactionid: z.string().max(250).optional(),
  productname: z.string().max(1200).optional(),
  productshortname: z.string().max(160).optional(),
  productcategory: z.string().max(500).optional(),
  productcolour: z.string().max(500).optional(),
  readytodispatchdate: z.number().optional(),
  delivereddate: z.number().optional(),
  cancelleddate: z.number().optional(),
  returneddate: z.number().optional(),
  orderstatus: z.string().max(500).optional(),
  uniqueordderid: z.string().max(500).optional(),
  orderlinenumber: z.string().max(500).optional(),
  deliveryfrom: z.string().max(500).optional(),
  location: z.string().max(500).optional(),
  dispatcheddate: z.number().optional(),
  ordereddate: z.number().optional(),
  paymentfaileddate: z.number().optional(),
  modifieddate: z.number().optional(),
}).passthrough();

export const upsertOrderlineSchema = z.object({
  id: z.number().optional(),
  orderid: z.number().optional(),
  productid: z.number().optional(),
  userid: z.number().optional(),
  addressid: z.number().optional(),
  productamount: z.number().optional(),
  discountamount: z.number().optional(),
  orderamount: z.number().optional(),
  quantity: z.number().optional(),
  merchanttransactionid: z.string().max(250).optional(),
  productname: z.string().max(1200).optional(),
  productshortname: z.string().max(160).optional(),
  productcategory: z.string().max(500).optional(),
  productcolour: z.string().max(500).optional(),
  readytodispatchdate: z.number().optional(),
  delivereddate: z.number().optional(),
  cancelleddate: z.number().optional(),
  returneddate: z.number().optional(),
  orderstatus: z.string().max(500).optional(),
  uniqueordderid: z.string().max(500).optional(),
  orderlinenumber: z.string().max(500).optional(),
  deliveryfrom: z.string().max(500).optional(),
  location: z.string().max(500).optional(),
  dispatcheddate: z.number().optional(),
  ordereddate: z.number().optional(),
  paymentfaileddate: z.number().optional(),
  createddate: z.number().optional(),
  modifieddate: z.number().optional(),
}).passthrough();

export const orderlineParamsSchema = z.object({
  id: z.string().min(1),
});

export type CreateOrderlineInput = z.infer<typeof createOrderlineSchema>;
export type UpdateOrderlineInput = z.infer<typeof updateOrderlineSchema>;
export type UpsertOrderlineInput = z.infer<typeof upsertOrderlineSchema>;
export type OrderlineParams = z.infer<typeof orderlineParamsSchema>;
