import { z } from 'zod';
import { dynamicFieldConfigs } from '../config/dynamicFieldConfig.js';
import { sanitizeProductRichText } from '../utils/productRichText.js';

const richTextField = z.string().transform(sanitizeProductRichText).optional();
const benefitItemSchema = z.object({
  icon: z.enum([
    'sparkles',
    'leaf',
    'shield',
    'repeat',
    'package',
    'heart',
    'droplet',
    'sun',
    'star',
    'wind',
  ]),
  text: z.string().trim().min(1, 'Benefit text is required').max(300, 'Benefit text is too long'),
});
const benefitItemsField = z.array(benefitItemSchema).max(12, 'A product can have at most 12 benefits').optional();
const requiredShortNameField = z.string()
  .trim()
  .min(2, 'Product short name is required and must be at least 2 characters')
  .max(160, 'Product short name must be no more than 160 characters');
const optionalShortNameField = requiredShortNameField.optional();

// Updated product schema for new database structure
export const createProductSchema = z.object({
  // Core required fields
  name: z.string().min(1, 'Product name is required').max(1200, 'Product name too long'),
  shortname: requiredShortNameField,
  puc: z.string().max(255, 'PUC too long').optional(), // Auto-generated by trigger
  
  // Product details
  shortdescription: richTextField,
  fulldescription: richTextField,
  benefititems: benefitItemsField,
  usage: richTextField,
  remarks: z.string().trim().min(1, 'Remarks are required').max(1000, 'Remarks too long'),
  category: z.string().max(255).optional(),
  subcategory: z.string().max(255).optional(),
  subsubcategory: z.string().max(255).optional(),
  fragnancetype: z.string().max(255).optional(),
  
  // Brand and packaging
  brand: z.string().max(255).optional(),
  pack: z.string().max(255).optional(), // Picklist value - validated at runtime against picklist table
  
  // Pricing
  price: z.number().positive('Price must be positive').optional(),
  discount: z.number().int().min(0).max(100, 'Discount cannot exceed 100%').optional(),
  averagerating: z.number().min(0).max(5, 'Rating must be between 0 and 5').optional(),
  
  // Quantity fields
  quantity: z.number().int().min(0).optional(),
  orderedquantity: z.number().int().min(0).optional(),
  soldquantity: z.number().int().min(0).optional(),
  availablequantity: z.number().int().min(0).optional(),
  ecompublishedquantity: z.number().int().min(0).optional(),
  damagedquantity: z.number().int().min(0).optional(),
  
  // Status
  productstatus: z.string().max(255).optional(),
  
  // Image arrays
  large: z.array(z.string()).optional(),
  medium: z.array(z.string()).optional(),
  small: z.array(z.string()).optional(),
  
  // Additional Product Information
  material: z.string().max(255).optional(),
  itemlength: z.string().max(255).optional(),
  manufacturer: z.string().max(255).optional(),
  netform: z.string().max(255).optional(),
  netquantity: z.string().max(255).optional(),
  numberofitems: z.number().int().min(0).optional(),
  itemthickness: z.string().max(255).optional(),
  
  // Product Dimensions & Weight (single unit)
  // Dimensions in cm - NUMERIC(10,2) - allows null for insert/update
  length: z.union([z.number().positive('Length must be positive'), z.null()]).optional(),
  width: z.union([z.number().positive('Width must be positive'), z.null()]).optional(),
  height: z.union([z.number().positive('Height must be positive'), z.null()]).optional(),
  // Weight in grams - NUMERIC(10,2) - allows null for insert/update
  weight: z.union([z.number().positive('Weight must be positive'), z.null()]).optional(),
  
  // Timestamps
  createddate: z.union([z.number(), z.bigint()]).optional(),
  modifieddate: z.union([z.number(), z.bigint()]).optional(),
  
  // Legacy field support
  isdealoftheday: z.boolean().optional(),
  status: z.string().optional(),
  description: z.string().optional(),
  
  // Combo Pack Support
  iscombo: z.boolean().optional().default(false),
  combotype: z.string().max(50).optional().default("fixed"),
  components: z.array(z.object({
    productid: z.union([z.string().regex(/^\d+$/), z.number(), z.bigint()]),
    requiredqty: z.number().int().min(1, 'Required quantity must be at least 1')
  })).optional(),
  
}).passthrough(); // Allow any additional fields

export const updateProductSchema = z.object({
  // All fields optional for updates - same as create but all optional
  name: z.string().min(1, 'Product name is required').max(1200, 'Product name too long').optional(),
  shortname: optionalShortNameField,
  puc: z.string().max(255, 'PUC too long').optional(), // Auto-generated by trigger
  
  // Product details
  shortdescription: richTextField,
  fulldescription: richTextField,
  benefititems: benefitItemsField,
  usage: richTextField,
  remarks: z.string().trim().min(1, 'Remarks are required').max(1000, 'Remarks too long').optional(),
  category: z.string().max(255).optional(),
  subcategory: z.string().max(255).optional(),
  subsubcategory: z.string().max(255).optional(),
  fragnancetype: z.string().max(255).optional(),
  
  // Brand and packaging
  brand: z.string().max(255).optional(),
  pack: z.string().max(255).optional(), // Picklist value - validated at runtime against picklist table
  
  // Pricing
  price: z.number().positive('Price must be positive').optional(),
  discount: z.number().int().min(0).max(100, 'Discount cannot exceed 100%').optional(),
  averagerating: z.number().min(0).max(5, 'Rating must be between 0 and 5').optional(),
  
  // Quantity fields
  quantity: z.number().int().min(0).optional(),
  orderedquantity: z.number().int().min(0).optional(),
  soldquantity: z.number().int().min(0).optional(),
  availablequantity: z.number().int().min(0).optional(),
  ecompublishedquantity: z.number().int().min(0).optional(),
  damagedquantity: z.number().int().min(0).optional(),
  
  // Status
  productstatus: z.string().max(255).optional(),
  
  // Image arrays
  large: z.array(z.string()).optional(),
  medium: z.array(z.string()).optional(),
  small: z.array(z.string()).optional(),
  
  // Additional Product Information
  material: z.string().max(255).optional(),
  itemlength: z.string().max(255).optional(),
  manufacturer: z.string().max(255).optional(),
  netform: z.string().max(255).optional(),
  netquantity: z.string().max(255).optional(),
  numberofitems: z.number().int().min(0).optional(),
  itemthickness: z.string().max(255).optional(),
  
  // Product Dimensions & Weight (single unit)
  length: z.number().positive('Length must be positive').optional(),
  width: z.number().positive('Width must be positive').optional(),
  height: z.number().positive('Height must be positive').optional(),
  weight: z.number().positive('Weight must be positive').optional(),
  
  // Timestamps
  createddate: z.union([z.number(), z.bigint()]).optional(),
  modifieddate: z.union([z.number(), z.bigint()]).optional(),
  
  // Legacy field support
  isdealoftheday: z.boolean().optional(),
  status: z.string().optional(),
  description: z.string().optional(),
  
}).passthrough();

export const upsertProductSchema = z.object({
  id: z.union([z.string().regex(/^\d+$/), z.number(), z.bigint()]).optional(),
  
  // Core fields - same as create/update
  name: z.string().min(1, 'Product name is required').max(1200, 'Product name too long').optional(),
  shortname: requiredShortNameField,
  puc: z.string().max(255, 'PUC too long').optional(), // Auto-generated by trigger
  
  // Product details
  shortdescription: richTextField,
  fulldescription: richTextField,
  benefititems: benefitItemsField,
  usage: richTextField,
  remarks: z.string().trim().min(1, 'Remarks are required').max(1000, 'Remarks too long').optional(),
  category: z.string().max(255).optional(),
  subcategory: z.string().max(255).optional(),
  subsubcategory: z.string().max(255).optional(),
  fragnancetype: z.string().max(255).optional(),
  
  // Brand and packaging
  brand: z.string().max(255).optional(),
  pack: z.string().max(255).optional(), // Picklist value - validated at runtime against picklist table
  
  // Pricing
  price: z.number().positive('Price must be positive').optional(),
  discount: z.number().int().min(0).max(100, 'Discount cannot exceed 100%').optional(),
  averagerating: z.number().min(0).max(5, 'Rating must be between 0 and 5').optional(),
  
  // Quantity fields
  quantity: z.number().int().min(0).optional(),
  orderedquantity: z.number().int().min(0).optional(),
  soldquantity: z.number().int().min(0).optional(),
  availablequantity: z.number().int().min(0).optional(),
  ecompublishedquantity: z.number().int().min(0).optional(),
  damagedquantity: z.number().int().min(0).optional(),
  
  // Status
  productstatus: z.string().max(255).optional(),
  
  // Image arrays
  large: z.array(z.string()).optional(),
  medium: z.array(z.string()).optional(),
  small: z.array(z.string()).optional(),
  
  // Additional Product Information
  material: z.string().max(255).optional(),
  itemlength: z.string().max(255).optional(),
  manufacturer: z.string().max(255).optional(),
  netform: z.string().max(255).optional(),
  netquantity: z.string().max(255).optional(),
  numberofitems: z.number().int().min(0).optional(),
  itemthickness: z.string().max(255).optional(),
  
  // Product Dimensions & Weight (single unit)
  length: z.number().positive('Length must be positive').optional(),
  width: z.number().positive('Width must be positive').optional(),
  height: z.number().positive('Height must be positive').optional(),
  weight: z.number().positive('Weight must be positive').optional(),
  
  // Timestamps
  createddate: z.union([z.number(), z.bigint()]).optional(),
  modifieddate: z.union([z.number(), z.bigint()]).optional(),
  
  // Legacy field support
  isdealoftheday: z.boolean().optional(),
  status: z.string().optional(),
  description: z.string().optional(),
  
}).passthrough();

export const productParamsSchema = z.object({
  id: z.string().regex(/^\d+$/, 'Invalid product ID - must be a numeric string'),
});

export const productQuerySchema = z.object({
  // Pagination
  page: z.string().optional(),
  limit: z.string().optional(),
  
  // Filter fields based on current schema
  name: z.string().optional(),
  shortname: z.string().optional(),
  category: z.string().optional(),
  subcategory: z.string().optional(),
  subsubcategory: z.string().optional(),
  fragnancetype: z.string().optional(),
  brand: z.string().optional(),
  pack: z.string().optional(), // Picklist value - validated at runtime against picklist table
  productstatus: z.string().optional(),
  minPrice: z.string().optional(),
  maxPrice: z.string().optional(),
  minQuantity: z.string().optional(),
  maxQuantity: z.string().optional(),
  minAvailableQuantity: z.string().optional(),
  maxAvailableQuantity: z.string().optional(),
  minSoldQuantity: z.string().optional(),
  maxSoldQuantity: z.string().optional(),
  minEcompublishedQuantity: z.string().optional(),
  maxEcompublishedQuantity: z.string().optional(),
  createdAfter: z.string().optional(),
  createdBefore: z.string().optional(),
  isdealoftheday: z.string().optional(),
  
  // Additional Product Information filters
  material: z.string().optional(),
  itemlength: z.string().optional(),
  manufacturer: z.string().optional(),
  netform: z.string().optional(),
  netquantity: z.string().optional(),
  numberofitems: z.string().optional(),
  itemthickness: z.string().optional(),
  searchtext: z.string().optional(),
});

// Dynamic field validation - now more permissive
export function validateProductDynamicFields(data: Record<string, any>): Record<string, any> {
  const config = dynamicFieldConfigs.product;
  const dynamicFields: Record<string, any> = {};
  
  for (const [key, value] of Object.entries(data)) {
    // Accept any field, but apply type conversion for known fields
    if (config && config.allowedFields.includes(key)) {
      const fieldType = config.fieldTypes[key];
      
      try {
        switch (fieldType) {
          case 'string':
            dynamicFields[key] = String(value);
            break;
          case 'number':
            dynamicFields[key] = Number(value);
            break;
          case 'boolean':
            dynamicFields[key] = Boolean(value);
            break;
          case 'date':
            dynamicFields[key] = new Date(value);
            break;
          default:
            dynamicFields[key] = value;
        }
      } catch (error) {
        // If type conversion fails, store as-is
        dynamicFields[key] = value;
      }
    } else {
      // For unknown fields, store as-is
      dynamicFields[key] = value;
    }
  }
  
  return dynamicFields;
}

export type CreateProductInput = z.infer<typeof createProductSchema>;
export type UpdateProductInput = z.infer<typeof updateProductSchema>;
export type UpsertProductInput = z.infer<typeof upsertProductSchema>;
export type ProductParams = z.infer<typeof productParamsSchema>;
export type ProductQuery = z.infer<typeof productQuerySchema>;
